### ISSUE TITLE
`variables` method at 0.21 returns undefined value in scalar context

### ISSUE THREAD

**Issue by bayashi** [bricas/uri-template#4]
Hi.

Before 0.20, `variables` method returns a number of list in scalar context.
However, at 0.21, `variables` method returns **undef** in scalar context actually.

    sub variables {
        return sort {$_[ 0 ]->{ _vars }->{ $a } <=> $_[ 0 ]->{ _vars }->{ $b } } keys %{ $_[ 0 ]->{ _vars } };
    }

The `sort` function returns **undef** in scalar context. It is different from `keys`
So, it is no good like below.

    if ( $uri_template_obj->variables ) {
        # something
    }

I expect It should be the same behavior as 0.20.
That returns the number of list in any context.
How do you think?

**Comment by bricas** [comment]
This should now be fixed in version 0.22 headed to CPAN.
