### ISSUE TITLE
Not following the RFC on + and # template placeholders

### ISSUE THREAD

**Issue by castaway** [bricas/uri-template#7]
Hi,

I'm contributing (as part of Shadowcat Systems), to work on the Paws API (https://github.com/pplu/aws-sdk-perl). Paws uses URI::Template, in a way specified with the RFC - it passes in pre-uri-encoded values for placeholders that are marked with a leading +, which are expected not to be encoded again - as stated here https://tools.ietf.org/html/rfc6570#section-3.2.1

It appears from the code that URI::Template treats +XX, #XX and XX all the same, and thus the values end up double-encoded.

Any thoughts? I will start looking into a patch.

**Comment by bricas** [comment]
I've just updated the test suite submodule to the latest commit and everything still passes.

A failing test case would be very helpful.

**Comment by castaway** [comment]
Yup, I also noticed it has none.. I've just found someone elses similar request on the Java uri template module.. but looks like nobody reported the issue back to the main test suite.. https://github.com/damnhandy/Handy-URI-Templates/issues/51

I will create some tests.

**Comment by castaway** [comment]
Here's my branch on uritemplates-test to add some, which I copied into t/cases to verify: https://github.com/castaway/uritemplate-test/tree/reserved-pct-encoded

**Comment by bricas** [comment]
Fixed in #8 and released in version 0.23. Cheers!
